apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app  
  template:
    metadata:
      labels:
        app: my-app  
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
